### YamlMime:Landing
title: Azure Arc Kubernetes (預覽)
summary: 了解如何使用 Azure Arc 管理 Kubernetes 叢集
metadata:
  title: Azure Arc Kubernetes
  description: 了解如何在 Azure 中管理內部部署機器
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: bc12e75904f375e2e40bce01d102186ec0d39f13
  ms.sourcegitcommit: 2c586a0fbec6968205f3dc2af20e89e01f1b74b5
  ms.translationtype: HT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 10/14/2020
  ms.locfileid: "92014251"
landingContent:
- title: 使用 Azure Arc 將 Kubernetes 叢集連線到 Azure
  linkLists:
  - linkListType: overview
    links:
    - text: 什麼是已啟用 Azure Arc 的 Kubernetes？
      url: overview.md
  - linkListType: quickstart
    links:
    - text: 連線叢集
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: 使用 GitOps 部署設定
      url: use-gitops-connected-cluster.md
    - text: 使用 GitOps 部署 Helm 圖表
      url: use-gitops-with-helm.md
    - text: 使用 Azure 原則強制執行 GitOps
      url: use-azure-policy.md
    - text: 部署 Azure IoT 邊線工作負載
      url: deploy-azure-iot-edge-workloads.md
- title: 參考架構
  linkLists:
  - linkListType: architecture
    links:
    - text: 管理混合式 Kubernetes 叢集的部署和組態
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
